//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.11

pub use super::article::Entity as Article;
pub use super::article_tag::Entity as ArticleTag;
pub use super::metadata::Entity as Metadata;
pub use super::tag::Entity as Tag;
